"""Regenerate indexes from references/websites/ (source of truth).

Regenerates:
  - INDEX.md
  - references/retrieval/industry-index.json
  - references/retrieval/style-index.json
  - references/retrieval/component-index.json

Merge strategy (keeps editorial value while staying in sync):
  - Structure (sites per industry/style, component files, notable entries) is derived
    from references/websites/*/metadata.json and analysis.md section 10.
  - Curated prose from the existing indexes (borrow/signature/take/pattern/collection)
    is preserved and keyed by name/slug; new sites/styles are appended.
  - references/retrieval/knowledge-map.json is editorial and is left untouched.

Collections (references/collections/*.md) are curated editorial content and are NOT
overwritten; INDEX.md lists them and validate.py checks their site references.

Usage:
    python scripts/rebuild.py
"""
from __future__ import annotations

import sys
from pathlib import Path

from _common import RETRIEVAL_DIR, WEBSITES_DIR, read_json, write_json

COMPONENT_ORDER = ["hero", "navbar", "logo-cloud", "features", "stats",
                   "testimonials", "pricing", "faq", "cta", "footer"]

COMPONENT_KEYWORDS = {
    "hero": ["hero"],
    "navbar": ["nav", "navbar"],
    "logo-cloud": ["logo cloud", "logo", "trust", "social proof", "proof band"],
    "features": ["feature", "how it works", "product deep-dive", "deep-dive", "benefit"],
    "stats": ["stat", "number", "proof"],
    "testimonials": ["testimonial", "quote", "creators"],
    "pricing": ["pricing", "plan", "price"],
    "faq": ["faq", "question"],
    "cta": ["cta", "call to action"],
    "footer": ["footer"],
}

SECTION_HEADER = """# INDEX.md — Design Skills Master Index

> Auto-generated by `scripts/rebuild.py`. Do not edit by hand.
> Read this after `SKILL.md`. Then use `references/retrieval/*.json` to load only what you need.
"""


def site_metadata() -> list[dict]:
    """Return metadata dicts for every website folder (skips _template)."""
    sites = []
    for folder in sorted(WEBSITES_DIR.iterdir()):
        if not folder.is_dir() or folder.name.startswith("_"):
            continue
        meta_path = folder / "metadata.json"
        if not meta_path.exists():
            print(f"  [warn] missing metadata.json in {folder.name}")
            continue
        try:
            meta = read_json(meta_path)
            meta["_dir"] = str(folder.name)
            sites.append(meta)
        except Exception as exc:  # noqa: BLE001
            print(f"  [warn] unreadable metadata.json in {folder.name}: {exc}")
    return sites


def parse_component_map(analysis_text: str) -> list[tuple[str, str]]:
    """Parse analysis.md section 10 into (label, note) pairs."""
    start = analysis_text.find("## 10. Component Map")
    if start == -1:
        return []
    chunk = analysis_text[start:]
    end = chunk.find("## 11.")
    if end != -1:
        chunk = chunk[:end]
    items = []
    for raw in chunk.splitlines():
        line = raw.strip()
        if not line or line.startswith("##"):
            continue
        m = __import__("re").match(r"^\d+\.\s*(.+)$", line)
        if not m:
            continue
        body = m.group(1)
        if "\u2014" in body:  # em dash separator used by analyses
            label, note = body.split("\u2014", 1)
        elif "-" in body:
            label, note = body.split("-", 1)
        else:
            label, note = body, ""
        items.append((label.strip(), note.strip().rstrip(".")))
    return items


def classify_component(label: str) -> str | None:
    low = label.lower()
    for comp, kws in COMPONENT_KEYWORDS.items():
        if any(kw in low for kw in kws):
            return comp
    return None


# ---------------------------------------------------------------- INDEX.md

def _title(name: str) -> str:
    return name.replace("-", " ").replace(".md", "").replace(".json", "").title()


def _file_table(dir_name: str, label: str) -> list[str]:
    d = Path(__file__).resolve().parent.parent / "references" / dir_name
    rows = [f"| {label} | File |", "|---|---|"]
    for f in sorted(d.glob("*")):
        if f.name.startswith(".") or f.name.startswith("_"):
            continue
        rows.append(f"| {_title(f.stem)} | `references/{dir_name}/{f.name}` |")
    return rows


def build_index_md(sites: list[dict]) -> str:
    lines = [SECTION_HEADER.rstrip(), "", "## Websites", "",
             "| Slug | Industry | Style | Theme | Layout |", "|---|---|---|---|---|"]
    for s in sites:
        lines.append(f"| {s['slug']} | {s['industry']} | {s['style']} | {s['theme']} | {s['layout']} |")
    lines += ["", "## Collections", ""]
    lines += _file_table("collections", "Category")
    lines += ["", "## Components", ""]
    lines += _file_table("components", "Component")
    lines += ["", "## Patterns (page assembly per industry)", ""]
    lines += _file_table("patterns", "Pattern")
    lines += ["", "## Design Tokens", ""]
    lines += _file_table("design-tokens", "System")
    lines += ["", "## Interaction Patterns", ""]
    lines += _file_table("interaction-patterns", "Pattern")
    lines += ["", "## Accessibility", ""]
    lines += _file_table("accessibility", "Topic")
    lines += ["", "## Retrieval Indexes", ""]
    lines += _file_table("retrieval", "Index")
    lines += ["", "## Prompts", ""]
    lines += _file_table("prompts", "Prompt")
    lines += ["", "## Processes (frontier UI-build method)", ""]
    lines += _file_table("processes", "Process")
    lines += ["", "## Copywriting (human copy, no AI patterns)", ""]
    lines += _file_table("copywriting", "Guide")
    lines += ["", "## Template", "",
              "| Item | File |", "|---|---|",
              "| New website template | `references/websites/_template/` |", ""]
    return "\n".join(lines)


# ------------------------------------------------------ retrieval indexes

def build_industry_index(sites: list[dict], prev: dict) -> dict:
    industries: dict[str, dict] = {}
    for s in sites:
        ind = s["industry"]
        industries.setdefault(ind, {"sites": []})
        industries[ind]["sites"].append({
            "slug": s["slug"], "name": s["name"],
            "style": s["style"], "theme": s["theme"],
        })
    old = prev.get("industries", {})
    for ind, data in industries.items():
        if ind in old:
            for k in ("pattern", "collection", "borrow"):
                if k in old[ind]:
                    data[k] = old[ind][k]
    return {
        "version": "1.0.0",
        "description": prev.get("description",
            "Industry -> references index. Open the listed analyses + pattern + collection, "
            "then synthesize. Source of truth: references/websites/*/metadata.json."),
        "industries": industries,
    }


def build_style_index(sites: list[dict], prev: dict) -> dict:
    styles: dict[str, dict] = {}
    for s in sites:
        st = s["style"]
        styles.setdefault(st, {"sites": []})
        styles[st]["sites"].append({
            "slug": s["slug"], "name": s["name"],
            "industry": s["industry"], "theme": s["theme"],
        })
    old = prev.get("styles", {})
    for st, data in styles.items():
        if st in old and "signature" in old[st]:
            data["signature"] = old[st]["signature"]
    return {
        "version": "1.0.0",
        "description": prev.get("description",
            "Style -> references index. Pick a target mood, open the listed analyses, "
            "then synthesize. Source of truth: references/websites/*/metadata.json."),
        "styles": styles,
        "notes": prev.get("notes",
            "Combine at least 2 styles deliberately to avoid copying a single site."),
    }


def build_component_index(prev: dict) -> dict:
    components: dict[str, dict] = {}
    for comp in COMPONENT_ORDER:
        components[comp] = {"file": f"references/components/{comp}.md", "notable": []}
    for folder in sorted(WEBSITES_DIR.iterdir()):
        if not folder.is_dir() or folder.name.startswith("_"):
            continue
        analysis = folder / "analysis.md"
        if not analysis.exists():
            continue
        for label, note in parse_component_map(analysis.read_text(encoding="utf-8")):
            comp = classify_component(label)
            if not comp or not note:
                continue
            components[comp]["notable"].append({"slug": folder.name, "take": note})
    old = prev.get("components", {})
    for comp, data in components.items():
        if comp in old:
            data["file"] = old[comp].get("file", data["file"])
            # drop stale notable entries; keep curated takes for surviving slugs
            old_takes = {n["slug"]: n["take"] for n in old[comp].get("notable", [])}
            seen: set[str] = set()
            kept = []
            for entry in data["notable"]:
                if entry["slug"] in seen:
                    continue
                seen.add(entry["slug"])
                if entry["slug"] in old_takes and old_takes[entry["slug"]]:
                    entry["take"] = old_takes[entry["slug"]]
                kept.append(entry)
            data["notable"] = kept
    return {
        "version": "1.0.0",
        "description": prev.get("description",
            "Component -> reference index. For each component, read the component guidance "
            "file, then open the notable site analyses before designing."),
        "components": components,
    }


def main() -> None:
    sites = site_metadata()
    print(f"rebuild: found {len(sites)} website(s)")
    (Path(__file__).resolve().parent.parent / "INDEX.md").write_text(
        build_index_md(sites), encoding="utf-8")
    print("  INDEX.md written")

    for name, builder in (
        ("industry-index", build_industry_index),
        ("style-index", build_style_index),
    ):
        path = RETRIEVAL_DIR / f"{name}.json"
        prev = read_json(path) if path.exists() else {}
        write_json(path, builder(sites, prev))
        print(f"  references/retrieval/{name}.json written")

    comp_path = RETRIEVAL_DIR / "component-index.json"
    comp_prev = read_json(comp_path) if comp_path.exists() else {}
    write_json(comp_path, build_component_index(comp_prev))
    print("  references/retrieval/component-index.json written")
    print("  (knowledge-map.json and collections/ are editorial; left untouched)")


if __name__ == "__main__":
    main()
    sys.exit(0)
